blank_issues_enabled: false
contact_links:
    - name: 🦁 LionForge Discord Server
      url: https://discord.gg/XyHp5GSXjx
      about: Ask questions, receive support, and discuss in our Discord server.
